sudo: required
dist: bionic
language: go
go:
  - "1.14.x"
install: 
  - sudo apt-get install -qq pkg-config fuse build-essential protobuf-compiler
cache:
  apt: true
jobs:
  include:
      - stage: build
        name: 'Ubuntu 18 Build Test'
        script:
          - go get -u -v github.com/golang/protobuf/proto
          - go get -u -v github.com/golang/protobuf/protoc-gen-go
          - protoc --go_out=. goproxy/*.proto
          - go run -race . -debug -test # test run with race
          - ./tests/http-proxy/build.sh
          - ./tests/tunnel/data-channel-create/build.sh
          - ./tests/tunnel/data-channel-wait/build.sh
          - go build -i -v -ldflags="-X 'main.GitHash=$(git describe --always --long --dirty)' -X 'main.Version=$(date +'%y.%m.%d')'" github.com/duality-solutions/web-bridge
          - ./web-bridge -debug -test