basePath: /api/v1
definitions:
  models.ConfigurationFile:
    properties:
      IceServers:
        items:
          $ref: '#/definitions/models.IceServerConfig'
        type: array
    type: object
  models.IceServerConfig:
    properties:
      Credential:
        description: The ICE server's credentials. Leave blank if it doesn't apply
        type: string
      URL:
        description: 'The ICE server''s full URL with protocol prefix and port: turn:ice.bdap.io:3478'
        type: string
      UserName:
        description: The ICE server's user name. Leave blank if it doesn't apply
        type: string
    type: object
  models.ImportMnemonicRequest:
    properties:
      language:
        description: 'Language (string, optional: english|french|chinesesimplified|chinesetraditional|italian|japanese|korean|spanish)'
        type: string
      mnemonic:
        description: Mnemonic (string, required) mnemonic delimited by the dash charactor (-) or space. Use 12 or 24 words
        type: string
      passphrase:
        description: Passphrase (string, optional) mnemonic passphrase used as the 13th or 25th word
        type: string
    type: object
  models.MnemonicResponse:
    properties:
      hdseed:
        description: HDSeed (string, required) deterministic wallet seed
        type: string
      mnemonic:
        description: Mnemonic (string, required) mnemonic associated with HD seed
        type: string
      mnemonicpassphrase:
        description: MnemonicPassphrase (string, optional)  mnemonic passphrase used as the 13th or 25th word
        type: string
    type: object
host: http://docs.webbridge.duality.solutions
info:
  contact:
    email: support@duality.solutions
    name: API Support
    url: http://www.duality.solutions/support
  description: WebBridge Rest API discovery website.
  license:
    name: Duality
    url: https://github.com/duality-solutions/web-bridge/blob/master/LICENSE.md
  termsOfService: http://www.duality.solutions/webbridge/terms
  title: WebBridge Restful API Documentation
  version: "1.0"
paths:
  /api/v1/ice:
    delete:
      consumes:
      - application/json
      description: Delete an ICE server in current configuration and saves the changes to file
      parameters:
      - description: ICE Configuration
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.IceServerConfig'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/models.IceServerConfig'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
    get:
      consumes:
      - application/json
      description: Returns all the ICE servers in current running configuration
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/models.IceServerConfig'
            type: array
        "500":
          description: Internal error
          schema:
            type: string
    post:
      consumes:
      - application/json
      description: Replaces an ICE server in current configuration and saves the changes to file
      parameters:
      - description: ICE Configuration File
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.ConfigurationFile'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.ConfigurationFile'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
    put:
      consumes:
      - application/json
      description: Add or update an ICE server in current configuration and saves the changes to file
      parameters:
      - description: ICE Configuration
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.IceServerConfig'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/models.IceServerConfig'
            type: array
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
  /api/v1/wallet/mnemonic:
    get:
      consumes:
      - application/json
      description: Shows the current wallet mnemonic and HD information
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/models.MnemonicResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
    post:
      consumes:
      - application/json
      description: Replaces the current wallet mnemonic with a new mnemonic
      parameters:
      - description: Mnemonic
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.ImportMnemonicRequest'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: Bad request
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
swagger: "2.0"
